name: py37
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.7.15=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - python=3.7.16=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - ale-py==0.8.1
    - antlr4-python3-runtime==4.8
    - asttokens==2.4.1
    - astunparse==1.6.3
    - async-timeout==4.0.3
    - asynctest==0.13.0
    - attrs==24.2.0
    - bypy==1.8.9
    - cachetools==5.5.2
    - cffi==1.15.1
    - charset-normalizer==3.4.1
    - click==8.1.8
    - cloudpickle==2.2.1
    - cycler==0.11.0
    - cython==3.0.12
    - dill==0.3.7
    - dm-env==1.6
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - easydict==1.13
    - efficientnet-pytorch==0.7.1
    - einops==0.6.1
    - filelock==3.12.2
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - ftfy==6.1.1
    - future==1.0.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - glfw==2.8.0
    - google-auth==2.40.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.62.3
    - gym==0.26.2
    - gym-notices==0.0.8
    - gymnasium==0.27.0
    - gymnasium-notices==0.0.1
    - huggingface-hub==0.16.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - idna==3.10
    - imageio==2.31.2
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - jax-jumpy==1.0.0
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - labmaze==1.0.6
    - lockfile==0.12.2
    - lxml==5.3.1
    - markdown==3.4.4
    - markdown-it-py==2.2.0
    - markupsafe==2.1.5
    - matplotlib==3.5.3
    - mdurl==0.1.2
    - mindspore==2.0.0
    - mindspore-ascend==1.10.0
    - mmcv==1.4.8
    - mmengine==0.10.7
    - mpmath==1.3.0
    - mujoco==2.3.5
    - multidict==6.0.5
    - multiprocess==0.70.15
    - networkx==2.6.3
    - numpy==1.21.6
    - oauthlib==3.2.2
    - omegaconf==2.1.2
    - opencv-python==4.12.0.88
    - packaging==24.0
    - pandas==1.3.5
    - pillow==9.5.0
    - platformdirs==4.0.0
    - protobuf==3.20.3
    - psutil==7.0.0
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pygments==2.17.2
    - pyopengl==3.1.9
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==1.2.5
    - pytz==2025.2
    - pywavelets==1.3.0
    - pyyaml==6.0.1
    - regex==2024.4.16
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - requests-toolbelt==1.0.0
    - rich==13.8.1
    - rsa==4.9.1
    - safetensors==0.3.3
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sentry-sdk==2.22.0
    - setproctitle==1.3.3
    - shimmy==0.2.1
    - six==1.17.0
    - smmap==5.0.2
    - spikingjelly==0.0.0.0.14
    - submitit==1.4.6
    - sympy==1.10.1
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - termcolor==2.3.0
    - thop==0.1.1-2209072238
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - timm==0.9.12
    - tomli==2.0.1
    - torch==1.12.1+cu113
    - torchaudio==0.12.1+cu113
    - torchmetrics==0.11.4
    - torchvision==0.13.1+cu113
    - tqdm==4.67.1
    - typing-extensions==4.7.1
    - urllib3==2.0.7
    - wandb==0.18.7
    - wcwidth==0.2.13
    - werkzeug==2.2.3
    - yapf==0.43.0
    - yarl==1.9.4
    - zipp==3.15.0
prefix: /home/user/cg/anaconda3/envs/py37
